<?php

namespace AppBundle\Repository;

/**
 * TeamMembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamMembersRepository extends \Doctrine\ORM\EntityRepository
{
}
