<?php

namespace AppBundle\Repository;

/**
 * tournament_bracket_teamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tournament_bracket_teamRepository extends \Doctrine\ORM\EntityRepository
{
}
