<?php

namespace AppBundle\Repository;

/**
 * tournament_teamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tournament_teamsRepository extends \Doctrine\ORM\EntityRepository
{
}
